#pragma once
#define IO_READ_MEMORY   CTL_CODE(FILE_DEVICE_UNKNOWN, 	0x804, 	METHOD_BUFFERED,FILE_ANY_ACCESS) //¿ØÖÆÂë²âÊÔ
#define IO_VIRTUAL_ALLOC_MEM_EX  CTL_CODE(FILE_DEVICE_UNKNOWN, 	0x805, 	METHOD_BUFFERED,FILE_ANY_ACCESS) //¿ØÖÆÂë²âÊÔ
#define IO_READ_MEMORY2   CTL_CODE(FILE_DEVICE_UNKNOWN, 	0x806, 	METHOD_BUFFERED,FILE_ANY_ACCESS) //¿ØÖÆÂë²âÊÔ


// ÐÂIRP
NTSTATUS  DeviceIoControl_Irp(PDEVICE_OBJECT device, PIRP pirp);
// ÀÏIRP
NTSTATUS DeviceIrpCtr(PDEVICE_OBJECT device, PIRP pirp);
//NTSTATUS  IRP_ReadProcessMemory2(PDEVICE_OBJECT device_Object, PIRP pirp);